use clew::ShortcutsRegistry;
use clew::{self as ui, SHORTCUTS_ROOT_SCOPE_ID};

pub fn init_shortcuts(shortcuts_registry: &mut ShortcutsRegistry) {
    let scope = shortcuts_registry
        .scope(ui::ShortcutScopes::TextEditing)
        .add_repeat(
            ui::TextEditingShortcut::Delete,
            ui::KeyBinding::new(ui::keyboard::KeyCode::Delete),
        )
        .add_repeat(
            ui::TextEditingShortcut::Backspace,
            ui::KeyBinding::new(ui::keyboard::KeyCode::Backspace),
        )
        .add_repeat(
            ui::TextEditingShortcut::MoveNext,
            ui::KeyBinding::new(ui::keyboard::KeyCode::ArrowRight),
        )
        .add_repeat(
            ui::TextEditingShortcut::MovePrev,
            ui::KeyBinding::new(ui::keyboard::KeyCode::ArrowLeft),
        )
        .add_repeat(
            ui::TextEditingShortcut::MoveUp,
            ui::KeyBinding::new(ui::keyboard::KeyCode::ArrowUp),
        )
        .add_repeat(
            ui::TextEditingShortcut::MoveDown,
            ui::KeyBinding::new(ui::keyboard::KeyCode::ArrowDown),
        )
        .add_repeat(
            ui::TextEditingShortcut::NextLine,
            ui::KeyBinding::new(ui::keyboard::KeyCode::Enter),
        )
        .add_repeat(
            ui::TextEditingShortcut::MoveStart,
            ui::KeyBinding::new(ui::keyboard::KeyCode::Home),
        )
        .add_repeat(
            ui::TextEditingShortcut::MoveEnd,
            ui::KeyBinding::new(ui::keyboard::KeyCode::End),
        )
        .add_repeat(
            ui::TextEditingShortcut::PageUp,
            ui::KeyBinding::new(ui::keyboard::KeyCode::PageUp),
        )
        .add_repeat(
            ui::TextEditingShortcut::PageDown,
            ui::KeyBinding::new(ui::keyboard::KeyCode::PageDown),
        )
        .add_modifier(
            ui::TextInputModifier::Select,
            ui::keyboard::KeyModifiers::shift(),
        );

    if cfg!(target_os = "macos") {
        scope
            .add_repeat(
                ui::TextEditingShortcut::BufferStart,
                ui::KeyBinding::new(ui::keyboard::KeyCode::Home).with_super(),
            )
            .add(
                ui::TextEditingShortcut::BufferEnd,
                ui::KeyBinding::new(ui::keyboard::KeyCode::End).with_super(),
            )
            .add(
                ui::TextEditingShortcut::SelectAll,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyA).with_super(),
            )
            .add_modifier(
                ui::TextInputModifier::Word,
                ui::keyboard::KeyModifiers::alt(),
            )
            .add_modifier(
                ui::TextInputModifier::Paragraph,
                ui::keyboard::KeyModifiers::alt(),
            )
            .add_repeat(
                ui::TextEditingShortcut::MoveStart,
                ui::KeyBinding::new(ui::keyboard::KeyCode::Home).with_super(),
            )
            .add_repeat(
                ui::TextEditingShortcut::MoveEnd,
                ui::KeyBinding::new(ui::keyboard::KeyCode::End).with_super(),
            );

        shortcuts_registry
            .scope(SHORTCUTS_ROOT_SCOPE_ID)
            .add(
                ui::CommonShortcut::Copy,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyC).with_super(),
            )
            .add(
                ui::CommonShortcut::Cut,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyX).with_super(),
            )
            .add_repeat(
                ui::CommonShortcut::Paste,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyV).with_super(),
            )
            .add_repeat(
                ui::CommonShortcut::Undo,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyZ).with_super(),
            )
            .add_repeat(
                ui::CommonShortcut::Redo,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyZ)
                    .with_super()
                    .with_shift(),
            );
    } else {
        scope
            .add_repeat(
                ui::TextEditingShortcut::BufferStart,
                ui::KeyBinding::new(ui::keyboard::KeyCode::Home).with_ctrl(),
            )
            .add(
                ui::TextEditingShortcut::BufferEnd,
                ui::KeyBinding::new(ui::keyboard::KeyCode::End).with_ctrl(),
            )
            .add(
                ui::TextEditingShortcut::SelectAll,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyA).with_ctrl(),
            )
            .add_modifier(
                ui::TextInputModifier::Word,
                ui::keyboard::KeyModifiers::ctrl(),
            )
            .add_modifier(
                ui::TextInputModifier::Paragraph,
                ui::keyboard::KeyModifiers::ctrl(),
            );

        shortcuts_registry
            .scope(SHORTCUTS_ROOT_SCOPE_ID)
            .add(
                ui::CommonShortcut::Copy,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyC).with_ctrl(),
            )
            .add(
                ui::CommonShortcut::Cut,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyX).with_ctrl(),
            )
            .add_repeat(
                ui::CommonShortcut::Paste,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyV).with_ctrl(),
            )
            .add_repeat(
                ui::CommonShortcut::Undo,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyZ).with_ctrl(),
            )
            .add_repeat(
                ui::CommonShortcut::Redo,
                ui::KeyBinding::new(ui::keyboard::KeyCode::KeyZ)
                    .with_ctrl()
                    .with_shift(),
            );
    }
}
